config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  #Login/logout routes for

  get '/login' => 'session#new'        # show login form
  post '/login' => 'session#create'    # form submits here, perform login, redirects
  delete '/login' => 'session#destroy' # logout link goes here, perform logout, redirect

# create all 7 CRUD routes for our User Model
resources :users

# create all & CRUD routes for TrainingPlan Model
resources :training_plans

# create all 7 CRUD routes for Workouts Model
resources :workouts

# create all 7 CRUD routes for Exercises Model
resources :exercises

end # Routes

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord

  has_and_belongs_to_many :workouts

end

app/models/training_plan.rb
class TrainingPlan < ApplicationRecord

  has_many :workouts, dependent: :destroy

  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :training_plans

  has_many :workouts, through: 'training_plans'

  has_secure_password

  validates :email, presence: true, uniqueness: true

  validates :name, length: { minimum: 2 }
end

app/models/workout.rb
class Workout < ApplicationRecord

  belongs_to :training_plan, optional: true

  has_many :users, through: 'training_plans'

  has_and_belongs_to_many :exercises

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # This fetch_user will run before every action of every controller
  before_action :fetch_user

  def fetch_user
    # check if the user_id in the session is a real one from our database then get the object for that user and save it in @current_user that will be used by every controller
    if session[:user_id].present?

      @current_user = User.find_by id: session[:user_id]


    end # if condition

    # if we get nil from the above user lookup query, then delet the session ( invalid )
    session[:user_id] = nil unless @current_user.present?

  end # fetch_user

  def check_if_logged_in
    # if current request is coming from a user who is not logged in we redirect them to the login page
    unless @current_user.present?
      flash[:error] = "You must be logged in to perform that action."

      redirect_to login_path

    end # unless

  end # check_if_logged_in

end # ApplicationController

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def new
  end

  def create
    exercise = Exercise.new exercise_params
    exercise.user_id = @current_user.id
    exercise.save
  end

  def index
    @exercises = Exercise.all
  end

  def show
    @exercise = Exercise.find params[:id]
  end

  def edit
    @exercise = Exercise.find params[:id]
    redirect_to login_path unless @exercise.user_id = @current_user.id
  end

  def update
  end

  def destroy
  end

  def exercise

    parames.require(:exercise).permit(:exercise_type)

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def home
  end

  def welcome

  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create

    # 1. Check if the email address entered is in the database
    user = User.find_by email: params[:email]

    # 2. Did we find a user for that email? If we found the user was the password correct?
    if user.present? && user.authenticate( params[:password])
      #credentials were correct - login successful

     # Create a special system variable called 'session' to be remembered across requests
     session[:user_id] = user.id

     redirect_to user

    else

      # If one of the conditions above weren't met then show the user an error
      flash[:error] = 'Invalid email or password'

      redirect_to login_path

    end #login Check

  end # create

  def destroy

    session[:user_id] = nil  #log out user
    redirect_to login_path

  end # destroy
end # SessionController

app/controllers/training_plans_controller.rb
class TrainingPlansController < ApplicationController
  def new

    @training_plan = TrainingPlan.new

    # Any workout not connected to a training_plan will be considered a template. Workout templates are shown to the user when they create a new training_plan(as a list of checkboxes), but we make copies of them and their exercises when we create a training plan. So we never assign the workout templates to a training plan, we only make copies.
    @workout_templates = Workout.where(training_plan_id: nil)

  end

  def create

    training_plan = TrainingPlan.new training_plan_params
    training_plan.user_id = @current_user.id
    training_plan.save
    workouts_to_copy = Workout.find(params[:training_plan][:workout_ids])
    workouts_to_copy.each do |w|
      new_workout = Workout.create workout_type: w.workout_type, training_plan_id: training_plan.id
      new_workout.exercises << w.exercises
    end

    redirect_to user_path(@current_user.id)

  end

  def index

    @training_plan = TrainingPlan.find params[:id]

  end

  def show

    @training_plan = TrainingPlan.find params[:id]

  end

  def edit

    # @workout_templates = Workout.where(training_plan_id: nil)
    @training_plan = TrainingPlan.find params[:id]
    @workout_templates = @training_plan.workouts

    redirect_to login_path unless @training_plan.user_id = @current_user.id

  end

  def update

    training_plan = TrainingPlan.find params[:id]

    if training_plan.user_id != @current_user.id
      redirect_to login_path
    end # if condition



    # training_plan.workouts.delete_all

    if params[:training_plan][:workout_ids].present?
      training_plan.workouts.each do |w|

        w.destroy unless params[:training_plan][:workout_ids].include?(w.id.to_s)
      end
      # training_plan.workouts << Workout.find(params[:training_plan][:workout_ids])
    else
      # if the workout_ids are not present, that means the user has unchecked all of the checkboxes that's why we are destroying them.
      training_plan.workouts.destroy_all
    end



    training_plan.update training_plan_params
    redirect_to training_plan_path

  end

  def destroy

    TrainingPlan.destroy params[:id]


    redirect_to user_path(@current_user.id)

  end

  def training_plan_params

    params.require(:training_plan).permit(:title, :goal)

  end #training_plan_params
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end # new users

  def create

    @user = User.create user_params

    #did the above .create actually save to the DB or not?
    if @user.persisted?
        #log the user automatically so they dont have to enter their details again
        session[:user_id] = @user.id


        redirect_to user_path(@user.id)

      else
        #we won't redirect to login_path

        # we render the template for the 'new' action i.e. blank form
        render :new

    end # if condition

  end #create

  def index

    @users = User.all

  end

  def show

    @user = User.find params[:id]

  end

  def edit

    @user = User.find params[:id]


  end

  def update

    @user = User.find params[:id]

    @user.update user_params
    redirect_to user_path(@user.id)

  end

  def destroy

    User.destroy params[:id]

    redirect_to root_path

  end


  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end # user_params


end # class UsersController

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  def new
  end

  def create

    workout = Workout.new workout_params
    workout.user_id = @current_user.id
    workout.save

  end

  def index

    @workouts = Workout.all

  end

  def show

    @workout = Workout.find params[:id]

  end

  def edit

    @workout = Workout.find params[:id]

    redirect_to login_path unless @workout.user_id = @current_user.id
    
  end

  def update

    workout = Workout.find params[:id]

    if workout.user_id != @current_user.id
      redirect_to login_path
    end # if condition

    workout.update workout_params
    redirect_to workout_path

  end

  def destroy
  end


  def workout

    params.require(:workout).permit(:workout_type)

  end # workout


end # WorkoutController

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/training_plans_helper.rb
module TrainingPlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/edit.html.erb
<h1>Exercises#edit</h1>
<p>Find me in app/views/exercises/edit.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<style>
@import url('https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap');
</style>

  <head>
  <meta name='image', property='og:image', content='https://ibb.co/K5c2Vx6'/>
  <meta property='og:title', content='What Workout' />
  <meta property='og:description', content='What workout is an app to motivate users to become healthier by creating a personalised workout plan where they can choose the exercises for that plan.'/>
  <meta property='og:url', content='//https://github.com/brunabdesouza/project1' />

    <title>What Workout</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>




  <body>

  <header>
    <nav>
        <div class="name">
          <h1><%= link_to "What Workout", root_path %></h1>
        </div>

          <div class="user">
            <% if @current_user.present? %>
              Welcome, <%= @current_user.name %>

            <%= link_to 'Logout', login_path, method: 'Delete' %></div>

              <div class="my_plans">
                <%= link_to 'My Training Plans', user_path(@current_user.id) %>
              </div>

            <% else %>
              <div class="first"><%= link_to 'Login', login_path %>

            <%= link_to 'Sign Up', new_user_path %>
        </div>

          <% end %>
    </nav>
    <hr>
  </header>



    <%= yield %>




    <div class="end">
    <footer>
      <hr>
      &copy; What Workout 2020
      </div>
    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<div class="main"><h1>How to Get Started</h1></div>

<div class="allhome">
<div id='home1'><p>First you create an account, <strong>it's Free!</strong></p></div>

<div id='home2'><p>Create a new Training Plan. You can choose the name of your plan and your goal.</p></div>

<div id='home3'><p>Select what type of workout you want to do and then add as many exercises as you want!</p></div>
</div>

app/views/session/new.html.erb
<div class="hello"><h2>Login</h2>

<% if flash[:error] %>
  <br>
    <strong>
      <%= flash[:error] %>
    </strong>
  <br>
  <br>
<% end %>
</div>

<!-- use form_with for generic forms, i.e. forms not connected to a model -  then we use 'url: someurl' instead of 'model:' -->
<%= form_with url:login_path, local: true do |f| %>

  <div class="formbody">
    <%= f.label :email %><br>
    <%= f.text_field :email %><br>
    <br>

    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
    <br>

    <%= f.submit  'Login' %>
  </div>

<% end %>

app/views/training_plans/_form.html.erb
<%= form_with model: @training_plan, local: true do |f| %>

<div class="formbody">
   <%= f.label :title %>
   <%= f.text_field :title %>
   <br>

   <%= f.label :goal %>
   <%= f.text_field :goal %>
   <br>
</div>

 <div class="checkbox">
   <%= f.label :workouts %>
   <%= f.collection_check_boxes :workout_ids, @workout_templates, :id, :workout_type, include_hidden: false do |b|
   b.label { b.check_box(checked: @training_plan.workouts.include?(b.object)) + b.text }
    end %>
   <br>
 </div>
  <br>

 <div class="formbody">
  <%= f.submit %>
 </div>

 <% end %>

app/views/training_plans/edit.html.erb
<div class="editplan">
<h1>Training Plan: <%= @training_plan.title %></h1>

<h3>
  Goal: <%= @training_plan.goal %>
</h3>

<h2>Edit your Training Plan</h2>
</div>
<%= render partial: 'form' %>

app/views/training_plans/index.html.erb
<h2>My Training Plans</h2>

<% @current_user.training_plans.each do |plan| %>
<li>

<%= link_to plan.title, training_plan_path(plan.id) %>

</li>


<% end %>

app/views/training_plans/new.html.erb
<div class="hello"><h2>New Training Plan</h2></div>

<%= render partial: 'form' %>

app/views/training_plans/show.html.erb
<div class="hello"><h2>
Training Plan: <%= @training_plan.title %>
</h2>

<h3>
  Goal: <%= @training_plan.goal %>
</h3>
</div>

<div class="lists">
  <div class="first_list"><p>Workout Type:
    <ul>
     <% @training_plan.workouts.each do |w|%>
       <li>
         <%= w.workout_type %>
       </li>
     </ul>
    </p>
  </div>

     <div class="second_list"><p>Exercise Type:
        <ul>
           <% w.exercises.each do |e| %>
          <li>
             <%= e.exercise_type %>
          </li>
          <% end %>
        </ul>
        </p>
      </div>
  <% end %>
<br>


<div class="edit_delete">
<%= link_to 'Edit Plan', edit_training_plan_path(@training_plan.id) %>

<%= link_to 'Delete Plan', training_plan_path(@training_plan.id), method: 'delete' %>
</div>
</div>

app/views/users/edit.html.erb
<div class="hello"><h2>Edit your details</h2></div>

<%= form_with model: @user, local: true, html: { multipart: true } do |f| %>

<div class="formbody">
<%= f.label :name%>
<%= f.text_field :name %>
<br>

<%= f.label :email%>
<%= f.text_field :email %>
<br>

<%= f.label :password%>
<%= f.password_field :password %>
<br>

<%= f.submit 'Update' %>
</div>
<% end %>

app/views/users/index.html.erb
<h2>Your Homepage</h2>


<ul>

<% @users.each do |user| %>

<li>

  <%= link_to user.name, user_path(user.id) %>

</li>

<% end %>

</ul>

app/views/users/new.html.erb
<div class="hello"><h2>Create an Account</h2></div>

<% if @user.errors.full_messages.any? %>
<strong>Please correct the following errors:</strong>
 <ul>
   <% @user.errors.full_messages.each do |error| %>
   <li><%= error %></li>
   <% end %>
 </ul>

 <% end %>

<%= form_with model: @user, local: true do |f| %>

<div class="formbody">
<%= f.label :name %>
<%= f.text_field :name %>
<br>

<%= f.label :email %>
<%= f.text_field :email %>
<br>

<%= f.label :password %>
<%= f.password_field :password %>
<br>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<br>

<%= f.submit 'Sign Up' %>
</div>

<% end %>

app/views/users/show.html.erb
<div class="hello">
  <h1>My Home</h1>
</div>

  <div class="details">
    <%= link_to 'Edit my Details', edit_user_path %>

    <%= link_to 'Delete Account', root_path %>
  </div>

  <div class="new_plan">
    <%= link_to 'New Training Plan', new_training_plan_path %>
  </div>

<div class="my_workouts">
  <div class="each_workout">
    <ul>
        <% @current_user.training_plans.each do |plan| %>

      <li>

        <%= link_to plan.title, training_plan_path(plan.id) %>

      </li>

        <% end %>

    </ul>
  </div>

</div>

app/views/workouts/index.html.erb
<h1>Workouts</h1>

<% @workouts.each do |work| %>

<%= link_to work.workout_type, workout_path(work.id) %>

<% end %>